services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: baronette-web
    restart: unless-stopped
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
#      - "traefik.http.routers.baronette.rule=Host(`baronette.es`) || Host(`www.baronette.es`)"
      - "traefik.http.routers.baronette.rule=Host(`preproduction.baronette.es`)"
      - "traefik.http.routers.baronette.entrypoints=websecure"
      - "traefik.http.routers.baronette.tls=true"
      - "traefik.http.services.baronette.loadbalancer.server.port=4321"

networks:
  traefik-net:
    external: true